version: '3.8'

services:
  bodega-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bodega_gestion_container
    ports:
      - "8080:80"
    restart: always
    environment:
      - NODE_ENV=production
    depends_on:
      - bodega-backend

  bodega-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bodega_backend_container
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
